const colorSelect = [
    { value: 'Albino', label: 'Albino' },
    { value: 'Apricot', label: 'Apricot' },
    { value: 'ASCOB', label: 'ASCOB' },
    { value: 'Ash', label: 'Ash' },
    { value: 'Badger', label: 'Badger' },
    { value: 'Banding', label: 'Banding' },
    { value: 'Beauty spot', label: 'Beauty spot' },
    { value: 'Belge', label: 'Belge' },
    { value: 'Belton', label: 'Belton' },
    { value: 'Bi-black', label: 'Bi-black' },
    { value: 'Bi-blue', label: 'Bi-blue' },
    { value: 'Biscuit', label: 'Biscuit' },
    { value: 'Black', label: 'Black' },
    { value: 'Black and silver', label: 'Black and silver' },
    { value: 'Black brindle', label: 'Black brindle' },
    { value: 'Blenheim', label: 'Blenheim' },
    { value: 'Blue fawn', label: 'Blue fawn' },
    { value: 'Blue roan', label: 'Blue roan' },
    { value: 'Boston', label: 'Boston' },
    { value: 'Brindlequin', label: 'Brindlequin' },
    { value: 'Bronzing', label: 'Bronzing' },
    { value: 'Buff', label: 'Buff' },
    { value: 'Butterfly nose', label: 'Butterfly nose' },
    { value: 'Charcoal', label: 'Charcoal' },
    { value: 'Check', label: 'Check' },
    { value: 'Chestnut', label: 'Chestnut' },
    { value: 'Chocolate', label: 'Chocolate' },
    { value: 'Cinnamon', label: 'Cinnamon' },
    { value: 'Clear-colored', label: 'Clear-colored' },
    { value: 'Copper', label: 'Copper' },
    { value: 'Cream', label: 'Cream' },
    { value: 'Creeping tan', label: 'Creeping tan' },
    { value: 'Cryptic merle', label: 'Cryptic merle' },
    { value: 'Dapple', label: 'Dapple' },
    { value: 'Dark merle', label: 'Dark merle' },
    { value: 'Deadgrass', label: 'Deadgrass' },
    { value: 'Deer', label: 'Deer' },
    { value: 'Dilute spot', label: 'Dilute spot' },
    { value: 'Domino', label: 'Domino' },
    { value: 'Dorsal stripe', label: 'Dorsal stripe' },
    { value: 'Dudley nose', label: 'Dudley nose' },
    { value: 'Fallow', label: 'Fallow' },
    { value: 'Fawn', label: 'Fawn' },
    { value: 'Fawnequin', label: 'Fawnequin' },
    { value: 'Fawn merle', label: 'Fawn merle' },
    { value: 'Flashy', label: 'Flashy' },
    { value: 'Flecking', label: 'Flecking' },
    { value: 'Flowered', label: 'Flowered' },
    { value: 'Formentino', label: 'Formentino' },
    { value: 'Ginger merle', label: 'Ginger merle' },
    { value: 'Gold', label: 'Gold' },
    { value: 'Grizzle', label: 'Grizzle' },
    { value: 'Harlequin', label: 'Harlequin' },
    { value: 'Havana Brown', label: 'Havana Brown' },
    { value: 'Isabella', label: 'Isabella' },
    { value: 'Ivory', label: 'Ivory' },
    { value: 'King Charles', label: 'King Charles' },
    { value: 'Lavender', label: 'Lavender' },
    { value: 'Lemon', label: 'Lemon' },
    { value: 'Light red (and red)', label: 'Light red (and red)' },
    { value: 'Lilac', label: 'Lilac' },
    { value: 'Lion', label: 'Lion' },
    { value: 'Mahogany', label: 'Mahogany' },
    { value: 'Maltese blue', label: 'Maltese blue' },
    { value: 'Mantle', label: 'Mantle' },
    { value: 'Mask', label: 'Mask' },
    { value: 'Merlequin (aka merlekin, merlikin)', label: 'Merlequin (aka merlekin, merlikin)' },
    { value: 'Minimal merle', label: 'Minimal merle' },
    { value: 'Mosaic', label: 'Mosaic' },
    { value: 'Mosaic spot', label: 'Mosaic spot' },
    { value: 'Muddy merle', label: 'Muddy merle' },
    { value: 'Mustard', label: 'Mustard' },
    { value: 'Onyx brindle', label: 'Onyx brindle' },
    { value: 'Orange', label: 'Orange' },
    { value: 'Particolor', label: 'Particolor' },
    { value: 'Pearl', label: 'Pearl' },
    { value: 'Pencilling', label: 'Pencilling' },
    { value: 'Pepper', label: 'Pepper' },
    { value: 'Phantom merle', label: 'Phantom merle' },
    { value: 'Pinto', label: 'Pinto' },
    { value: 'Pips', label: 'Pips' },
    { value: 'Platinum', label: 'Platinum' },
    { value: 'Plattenhunde', label: 'Plattenhunde' },
    { value: 'Points', label: 'Points' },
    { value: 'Porcelaine', label: 'Porcelaine' },
    { value: 'Powder merle', label: 'Powder merle' },
    { value: 'Prince Charles', label: 'Prince Charles' },
    { value: 'Red', label: 'Red' },
    { value: 'Red speckle', label: 'Red speckle' },
    { value: 'Reverse brindle', label: 'Reverse brindle' },
    { value: 'Ruby', label: 'Ruby' },
    { value: 'Russet', label: 'Russet' },
    { value: 'Rust', label: 'Rust' },
    { value: 'Sable', label: 'Sable' },
    { value: 'Salt and pepper', label: 'Salt and pepper' },
    { value: 'Sandy', label: 'Sandy' },
    { value: 'Seal', label: 'Seal' },
    { value: 'Sedge', label: 'Sedge' },
    { value: 'Sesame', label: 'Sesame' },
    { value: 'Silver brindle', label: 'Silver brindle' },
    { value: 'Slate', label: 'Slate' },
    { value: 'Slate merle', label: 'Slate merle' },
    { value: 'Sooty', label: 'Sooty' },
    { value: 'Spectacles', label: 'Spectacles' },
    { value: 'Splash coat', label: 'Splash coat' },
    { value: 'Stag ', label: 'Stag ' },
    { value: 'Tan ', label: 'Tan ' },
    { value: 'Tawny', label: 'Tawny' },
    { value: 'Tiger brindle', label: 'Tiger brindle' },
    { value: 'Tricolor', label: 'Tricolor' },
    { value: 'Trim', label: 'Trim' },
    { value: 'Trindle', label: 'Trindle' },
    { value: 'Tweed (tweed merle)', label: 'Tweed (tweed merle)' },
    { value: 'Urajiro', label: 'Urajiro' },
    { value: 'Vent marking', label: 'Vent marking' },
    { value: 'Wheaten', label: 'Wheaten' },
    { value: 'White collar', label: 'White collar' },
    { value: 'Widow\'s peak', label: 'Widow\'s peak' },
    { value: 'Wolf grey', label: 'Wolf grey' },
    { value: 'Yellow', label: 'Yellow' }
  ];

  const resources = {
    colorSelect
};

export default resources;